import ThemeRegistry from '@/theme/ThemeRegistry'
import type { Metadata } from 'next'
import {Ubuntu } from 'next/font/google'
import Head from 'next/head'

const ubuntu = Ubuntu({ subsets: ['latin-ext'], weight: ['300', '400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" data-color-scheme="dark">
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <body className={ubuntu.className}>
        <ThemeRegistry>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  )
}
